import type { AnalyzeResponse, SavedProfile } from "./types";

export const MOCK_RESPONSE: AnalyzeResponse = {
  business_type: "restaurant",
  business_label: "Restaurant",
  location: "Koreatown",
  features: ["liquor", "outdoor_dining"],
  summary:
    "A restaurant with alcohol service and outdoor dining in Koreatown requires permits from multiple city, county, and state agencies. The ABC liquor license can take 2–6 months to process — start this application early. A Public Health Permit from LACDPH is required before opening, and an Outdoor Dining Permit is needed for any patio or sidewalk seating. A Certificate of Occupancy must be obtained before opening to the public.",
  checklist: [
    {
      id: "business_tax_registration",
      title: "Business Tax Registration Certificate (BTRC)",
      status: "required",
      priority: "critical",
      category: "licenses",
      detail: "Required for all businesses operating within the City of Los Angeles. Registers the business with the Office of Finance for tax purposes.",
      agency: "City of Los Angeles",
      fee: "$0–$500/year",
      timeline: "1–2 weeks",
      renewal: "Annual",
    },
    {
      id: "ein",
      title: "Employer Identification Number (EIN)",
      status: "required",
      priority: "critical",
      category: "licenses",
      detail: "Federal tax ID required for bank accounts, hiring, and tax filings. Free from IRS.",
      agency: "Federal Government",
      fee: "Free",
      timeline: "Immediate (online)",
      renewal: "None — permanent",
    },
    {
      id: "health_permit",
      title: "Health Permit (Public Health)",
      status: "required",
      priority: "critical",
      category: "permits",
      detail: "Required before serving food. LACDPH inspects sanitation, ventilation, food storage, and hygiene practices.",
      agency: "LA County Dept. of Public Health",
      fee: "$700–$2,000",
      timeline: "4–8 weeks",
      renewal: "Annual",
    },
    {
      id: "fire_clearance",
      title: "Fire Department Clearance",
      status: "pending",
      priority: "critical",
      category: "inspections",
      detail: "LAFD inspects fire safety, occupancy capacity, exit signage, and sprinkler systems.",
      agency: "Los Angeles Fire Department",
      fee: "$200–$500",
      timeline: "2–4 weeks",
      renewal: "Annual inspection",
    },
    {
      id: "certificate_of_occupancy",
      title: "Certificate of Occupancy",
      status: "pending",
      priority: "critical",
      category: "zoning",
      detail: "Required before opening. Confirms compliance with zoning, building code, and safety requirements.",
      agency: "LA Dept. of Building and Safety",
      fee: "Included with building permit",
      timeline: "2–6 weeks after final inspection",
      renewal: "Per change of use",
    },
    {
      id: "abc_license",
      title: "ABC Liquor License",
      status: "required",
      priority: "high",
      category: "licenses",
      detail: "Required to sell or serve alcoholic beverages. Type 41 (beer/wine) or Type 47 (full liquor). Start early — processing takes months.",
      agency: "CA Dept. of Alcoholic Beverage Control",
      fee: "$1,000–$15,000+",
      timeline: "2–6 months",
      renewal: "Annual",
    },
    {
      id: "outdoor_dining_permit",
      title: "Sidewalk / Outdoor Dining Permit",
      status: "required",
      priority: "medium",
      category: "permits",
      detail: "Required for dining on public sidewalks or rights-of-way. Site plan with pedestrian clearance and ADA compliance required.",
      agency: "City of Los Angeles",
      fee: "$500–$2,000",
      timeline: "4–8 weeks",
      renewal: "Annual",
    },
    {
      id: "sellers_permit",
      title: "Seller's Permit",
      status: "required",
      priority: "critical",
      category: "licenses",
      detail: "Required by CDTFA for collecting California sales tax on food sales.",
      agency: "CA Dept. of Tax and Fee Administration",
      fee: "Free",
      timeline: "1–2 weeks",
      renewal: "None unless business changes",
    },
  ],
  sources: [
    { title: "LA County Food Facility Health Permit", agency: "LACDPH Environmental Health", score: 0.91 },
    { title: "ABC Retail License Types — Type 47", agency: "CA Dept. of Alcoholic Beverage Control", score: 0.87 },
    { title: "Outdoor Dining Permit Requirements", agency: "City of Los Angeles LADOT", score: 0.83 },
  ],
  mock: true,
};

export const MOCK_PROFILES: SavedProfile[] = [
  {
    id: "profile-1",
    businessName: "Seoul Kitchen",
    businessType: "restaurant",
    businessLabel: "Restaurant",
    location: "Koreatown",
    savedAt: "2026-04-20",
    itemCounts: { required: 5, pending: 2, compliant: 1 },
    data: MOCK_RESPONSE,
  },
  {
    id: "profile-2",
    businessName: "Silver Lake Cuts",
    businessType: "salon",
    businessLabel: "Hair/Beauty Salon",
    location: "Silver Lake",
    savedAt: "2026-04-18",
    itemCounts: { required: 3, pending: 1, compliant: 2 },
    data: {
      ...MOCK_RESPONSE,
      business_type: "salon",
      business_label: "Hair/Beauty Salon",
      location: "Silver Lake",
      features: [],
    },
  },
  {
    id: "profile-3",
    businessName: "DTLA Tacos",
    businessType: "food_truck",
    businessLabel: "Food Truck",
    location: "Downtown LA",
    savedAt: "2026-04-15",
    itemCounts: { required: 4, pending: 2, compliant: 0 },
    data: {
      ...MOCK_RESPONSE,
      business_type: "food_truck",
      business_label: "Food Truck",
      location: "Downtown LA",
      features: [],
    },
  },
];
